### ISSUE TITLE
Question & Hint @possible copy/paste/oversight bug

### ISSUE THREAD

**Issue by joehannes** [active-group/active-clojure#38]
We are trying to use your lib in our greenfield project, and I'm trying to get into this lib although I'm new to clojure and there's little documentation (only the README???).
We are about to test our first attempts with this lib and I already successfully ran my tests in the REPL.
I was wondering if the thing would work in the FE as well, as the cljc files where we `define-record-type` import bespoke 'define-record-type' from active.clojure.record only and I don't take active.clojure.cljs.record into account.

1. Can you let me know if this is necessary for the cljs parts to run (=FE)
2. If so, I want to report a probable bug:

I had a look at the files in order to understand this myself and found that the `define-record-type` methods as defined in
`https://github.com/active-group/active-clojure/blob/master/src/active/clojure/cljs/record.cljc` are defined for
* .clj again, and not *.cljs ... so this clearly seems to be a slight copy/paste oversight if I'm not mistaken

Please let me know. Also, is there some more documentation somewhere???

**Comment by kaaninho** [comment]
Yes, it is necessary, because `define-record-type` is a macro. You cannot define a macro in plain CLJS files, ClojureScript has no macros, but uses Clojure for defining them. Usually you'd have an extra CLJ file for your macro and require that in the CLJS file via `:require-macros`/`:include-macros`. But it is also possible to create a CLJC file that contains the code for the CLJ parts (macros) and the CLJS parts. Here you need to provide `#?(:clj` if you want to tell the reader to only evaluate the following form if its the Clojure reader.

`README.md` is the only documentation: https://cljdoc.org/d/de.active-group/active-clojure/0.37.1/doc/readme .

The test namespace `active.clojure.record-test` provides many examples and usages.

To use `define-record-type` in your project in a CLJS file, you have to add `[active.clojure.cljs.record :as rec :include-macros true]` to your namespace declaration.

If you have further questions feel free to contact us!

**Comment by joehannes** [comment]
Hey!

Thx a lot for your reply..

Also, actually I got a further question:

Can you tell me where my point of failure is regarding your lib and my REPL?

Scenario:
nvim + luminus template setup with leiningen + conjure-plugin + lein repl

If I got all my specs in one file and evaluate that buffer via conjure in the REPL it works.
I just need to evaluate all the dependency-files ... first

But if there are specs I depend on in one of those other files and I evaluate them first:
It seems the REPL seems to forget those ...
I don't really know, I just read there's something like a global registry with specs ..
But anyway, the REPL doesn't remember specs from previously evaluated buffers/files.

Can you point me to a solution/direction.

My problem is I don't know my probable point of failure:
Is it my nvim + repl setup?
Is there something else wrong?
Does it not work this way??

Since I kinda think it should probably work automatically, also that the REPL probably should import the files dependent on automatically,
I thought probably it's my REPL setup.

But then if I spent X time during work trying to figure that out when in reality it's something completely different ... I don't like the idea.

Maybe you can shed some light.

Cheers, J

**Comment by kaaninho** [comment]
Hi,

is your initial problem now solved? If that's the case I'd close this issue.

I think I don't have these REPL issues on my machine and setup. I am using Emacs and I've never used your setup so I can't tell you, if the the setup is the problem.

But I am not sure because it could be that I don't understand your issue fully.

**Comment by joehannes** [comment]
I guess you can close the issue.
I understood it's not a bug but there's the necessity for cljc code to run clj code on cljs side of things ...

thinking about it, I don't get it though and it seems impossible.
reading your first email response again it kinda makes some sense due to the macro issue.

well, you know, if it's not a bug it should work when I run it on cljs later (the defrecord thingies) and there's no prob.
(can't test it yet outside of the repl, missing code .. hehe)
so I guess I'm happy and you should be able to close the tag anyway :-)

ok, thx for your help, appreciated :-)

Cheers, J
